# Use "" to remove. Yes, you can remove all plugin messages entirely (do not recommend).
messages:
  reloaded: "&8[&2DoubleJump&8] &aConfiguration reloaded!"
  permission: "&cYou dont have permission to do that!"
  jump: "&aYeet!"

# Spreading particle type.
particles:
  in-start: true
  in-trace: true

# Jump forces multipliers.
jump-forces:
  forward: 1.3
  up: 1.0

# Particle count in-start spreading type. It doesn't matter if they are disabled.
# Recommends: Don't use large numbers, that can cause server lags!
count: 12

# List of all particles: https://helpch.at/docs/1.12.2/org/bukkit/Particle.html
particle: CLOUD

# List of all sounds: https://helpch.at/docs/1.12.2/org/bukkit/Sound.html
sound: ENTITY_FIREWORK_LAUNCH

# Worlds in which the plugin will work.
enabled-world:
  - world
# - lobby
# - hub
