# Use "" to remove. Yes, you can remove all plugin messages entirely (do not recommend).
messages:
  reloaded: "&8[&2DoubleJump&8] &aConfiguration reloaded!"
  permission: "&cYou dont have permission to do that!"
  jump: "&aYeet!"

# List of all particles: https://helpch.at/docs/1.12.2/org/bukkit/Particle.html
# Particles when the player double jump.
start:
  enabled: true
  particle: CLOUD
  count: 12
# Particles behind the player after double jump.
trace:
  enabled: true
  particle: FLAME
  count: 3

# List of all sounds: https://helpch.at/docs/1.12.2/org/bukkit/Sound.html
# Use "" to remove.
sound: ENTITY_FIREWORK_LAUNCH
  
# Jump forces multipliers.
jump-forces:
  forward: 1.3
  up: 1.0

# Worlds in which the plugin will work.
enabled-world:
  - world
# - lobby
# - hub