name: DoubleJump
version: 1.2.1
description: This plugin allows your players to use "double jump" in hub. (thanks Fabricio20 for the idea)
author: LamberKeep
main: com.myvnc.exo.Main

commands:
  doublejump:
    description: DoubleJump commands

permissions:
  doublejump.admin:
    description: Allows to use admins commands.
    default: op  
  doublejump.jump:
    description: Allows to double jump.
    default: true
